version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: jamlydb
    environment:
      POSTGRES_USER: jamadmin
      POSTGRES_PASSWORD: jampass
      POSTGRES_DB: jamlydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
